name: Automated Translations

on:
  pull_request:
    paths:
      - 'src/**/*.{ts,tsx}'
      - 'src/providers/i18n/locales/**/*.json'

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install
          bun pm ls

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run translations
        env:
          LANGUINE_API_KEY: ${{ secrets.LANGUINE_API_KEY }}
        run: |
          bun run languine:translate

      - name: Check for changes
        id: git-check
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git checkout -b pr-${{ github.event.pull_request.number }}
          git commit -m "chore: update translations [skip ci]"
          git push origin pr-${{ github.event.pull_request.number }}:${{ github.event.pull_request.head.ref }}
